language: bash

services:
  - docker

matrix:
  fast_finish: true

env:
  global:
    - SHELLCHECK_VERSION=0.7.1 IMAGE=essentialkaos/perfecto:centos7

before_install:
  - wget https://github.com/koalaman/shellcheck/releases/download/v${SHELLCHECK_VERSION}/shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz
  - tar xf shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz
  - mv shellcheck-v${SHELLCHECK_VERSION} shellcheck-latest
  - ./shellcheck-latest/shellcheck --version
  - docker pull "$IMAGE"
  - wget https://kaos.sh/perfecto/perfecto-docker
  - chmod +x perfecto-docker

script:
 - .travis/script.sh SOURCES/defs
 - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck install.sh'
 - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck SOURCES/rbdef'
 - bash -c 'shopt -s globstar; ./shellcheck-latest/shellcheck SOURCES/rbbuild SOURCES/blds/*'
 - ./perfecto-docker rbbuild.spec
 - ./perfecto-docker rbbuild-defs.spec
