#!/usr/bin/env bash
# shellcheck disable=SC2034,SC2086,SC2154

################################################################################

if [[ -n "${SCRIPT_DEBUG}" ]] ; then
  set -x
fi

################################################################################

# App name (String)
APP="RBBuild"

# App version (String)
VER="2.4.1"

################################################################################

NORM=0
BOLD=1
ITLC=3
UNLN=4
RED=31
GREEN=32
YELLOW=33
BLUE=34
MAG=35
CYAN=36
GREY=37
DARK=90

CL_NORM="\e[${NORM}m"
CL_BOLD="\e[${BOLD}m"
CL_ITLC="\e[${ITLC}m"
CL_UNLN="\e[${UNLN}m"
CL_RED="\e[${RED}m"
CL_GREEN="\e[${GREEN}m"
CL_YELLOW="\e[${YELLOW}m"
CL_BLUE="\e[${BLUE}m"
CL_MAG="\e[${MAG}m"
CL_CYAN="\e[${CYAN}m"
CL_GREY="\e[${GREY}m"
CL_DARK="\e[${DARK}m"
CL_BL_RED="\e[${BOLD};${RED}m"
CL_BL_GREEN="\e[${BOLD};${GREEN}m"
CL_BL_YELLOW="\e[${BOLD};${YELLOW}m"
CL_BL_BLUE="\e[${BOLD};${BLUE}m"
CL_BL_MAG="\e[${BOLD};${MAG}m"
CL_BL_CYAN="\e[${BOLD};${CYAN}m"
CL_BL_GREY="\e[${BOLD};${GREY}m"
CL_IT_DARK="\e[${ITLC};${DARK}m"
CL_BG_RED="\e[7m${CL_RED}"
CL_BG_GREEN="\e[7m${CL_GREEN}"
CL_BG_YELLOW="\e[7m${CL_YELLOW}"
CL_BG_BLUE="\e[7m${CL_BLUE}"
CL_BG_MAG="\e[7m${CL_MAG}"
CL_BG_CYAN="\e[7m${CL_CYAN}"
CL_BG_GREY="\e[7m${CL_GREY}"

################################################################################

SUPPORTED_OPTS="dest_dir !help mirror output !quiet tmp threads 
 !verbose !version cc_comp cxx_comp !mirror_list !ignore_checksums dl_cache 
 !rbenv name proxy !debug !yes !no_patch !no_color !no_spinner 
 !ignore_loadavg !continue"

SHORT_OPTS="h:!help d:dest_dir m:mirror o:output q:!quiet T:tmp N:name 
 t:threads V:!verbose v:!version y:!yes P:proxy L:!mirror_list D:!debug 
 ic:!ignore_checksums dc:dl_cache r:!rbenv cc:cc_comp cxx:cxx_comp 
 np:!no_patch nc:!no_color ns:!no_spinner il:!ignore_loadavg C:!continue"

################################################################################

# Path to libexec directory
LIBEXEC_DIR="/usr/libexec/rbbuild"

# Path to directory with def files
DEFS_DIR="/usr/local/share/rbbuild"

################################################################################

# Maximum lines from log for failed build (Number)
LOG_TAIL_SIZE=30

# Maximum redirects during download process (Number)
MAX_REDIRS=10

# Maximum load avearage (Number)
MAX_LA=5

################################################################################

CWD=$(pwd)
PID="$$"

################################################################################

output=/dev/tty
verb_output=/dev/null
tmp="/var/tmp"

log=""
tmp_dir=""
def_file=""
require_patching=""
require_autoconf=""

mirror="${mirror:-default}"

################################################################################

ruby_bin=$(command -v "ruby")
java_bin=$(command -v "java")

################################################################################

declare -A allowed_vars=(
  ["prefix"]="1"
  ["os_name"]="1"
  ["os_arch"]="1"
  ["os_arch_alt"]="1"
  ["os_arnm"]="1"
  ["os_dist"]="1"
  ["os_kern"]="1"
  ["gcc_version"]="1"
  ["clang_version"]="1"
  ["java_version"]="1"
  ["ruby_version"]="1"
)

################################################################################

declare -A _requires

################################################################################

main() {
  if [[ ! -c /dev/stdout || -n "$no_color" || -n "$NO_COLOR" ]] ; then
    unset NORM BOLD CL_ITLC UNLN RED GREEN YELLOW BLUE MAG CYAN GREY DARK
    unset CL_NORM CL_BOLD CL_UNLN CL_RED CL_GREEN CL_YELLOW CL_BLUE CL_MAG CL_CYAN CL_GREY CL_DARK
    unset CL_BL_RED CL_BL_GREEN CL_BL_YELLOW CL_BL_BLUE CL_BL_MAG CL_BL_CYAN CL_BL_GREY CL_IT_DARK
    unset CL_BG_RED CL_BG_GREEN CL_BG_YELLOW CL_BG_BLUE CL_BG_MAG CL_BG_CYAN CL_BG_GREY
    no_color=true
  fi

  if [[ -n "$version" ]] ; then
    about
    exit 0
  fi

  if [[ -n "$help" ]] ; then
    usage
    exit 0
  fi

  if [[ ! -c /dev/stdout ]] ; then
    require "list"
    list.file "$@"
    return $?
  fi

  show ""

  if [[ -n "$mirror_list" ]] ; then
    require "list"
    list.mirrors "$@"
  elif [[ $# -eq 0 ]] ; then
    require "list"
    list.defs
  else
    require "build"
    build.start "$@"
  fi

  show ""

  finish $?
}

# Load libexec script
#
# 1: Script name without extension (String)
#
# Code: No
# Echo: No
require() {
  local script="${1}.shx"

  # File already loaded, skip it
  if [[ "${_requires[$script]}" -eq 1 ]] ; then
    return
  fi

  if [[ ! -e "$LIBEXEC_DIR/$script" ]] ; then
    error "Can't find file $script in libexec directory ($LIBEXEC_DIR)"
    exit 1
  fi

  if [[ ! -r "$LIBEXEC_DIR/$script" ]] ; then
    error "File $LIBEXEC_DIR/$script is not readable"
    exit 1
  fi

  if [[ ! -s "$LIBEXEC_DIR/$script" ]] ; then
    error "File $LIBEXEC_DIR/$script is empty"
    exit 1
  fi

  _requires[$script]=1

  # shellcheck disable=SC1090
  source "$LIBEXEC_DIR/$script"
}

# Finish script execution
#
# 1: Exit code (Number)
#
# Code: No
# Echo: No
finish() {
  if [[ -z "$debug" && -d "$tmp_dir" ]] ; then
    rm -rf "$tmp_dir" &> /dev/null
  fi

  if [[ "$CWD" != "$(pwd)" ]] ; then
    cd "$CWD" || exit 1
  fi

  exit "${1:-0}"
}

################################################################################

# Show message
#
# 1: Message (String)
# 2: Color code (Number) [Optional]
#
# Code: No
# Echo: No
show() {
  if [[ -n "$2" && -z "$no_colors" ]] ; then
    echo -e "\e[${2}m${1}\e[0m"
  else
    echo -e "$*"
  fi
}

# Show message without newline symbol
#
# 1: Message (String)
# 2: Color (Number) [Optional]
#
# Code: No
# Echo: No
showm() {
  if [[ -n "$2" && -z "$no_colors" ]] ; then
    echo -e -n "\e[${2}m${1}\e[0m"
  else
    echo -e -n "$*"
  fi
}

# Show message about executed build command
#
# *: Command with arguments
#
# Code: No
# Echo: No
showc() {
  local win_width

  win_width=$(stty size 2>/dev/null | cut -f2 -d' ')

  printf "\n${CL_BOLD}\e[48;5;57m%-${win_width:-88}s${CL_NORM}\n\n" " → $*"
}

# Show formatted message with option info
#
# 1: Option (String)
# 2: Description (String)
# 3: Arguments (String) [Optional]
#
# Code: No
# Echo: No
showo() {
  local optn optd optp optt optf breadcrumbs

  optn="$1"
  optd="$2"
  optp="$3"

  if [[ -n "$DARK" ]] ; then
    breadcrumbs="............................"
  else
    breadcrumbs="                            "
  fi

  if [[ -z "$optp" ]] ; then
    optt="$optn"
    optf=$(( 26 - ${#optt} ))
    echo -e "  ${CL_GREEN}${optn}${CL_NORM} ${CL_DARK}${breadcrumbs:0:$optf}${CL_NORM} $optd"
  else
    optt="$optn $optp"
    optf=$(( 26 - ${#optt} ))
    echo -e "  ${CL_GREEN}${optn}${CL_NORM} ${CL_GREY}${optp}${CL_NORM} ${CL_DARK}${breadcrumbs:0:$optf}${CL_NORM} $optd"
  fi
}

# Print error message
#
# 1: Message (String)
#
# Code: No
# Echo: No
error() {
  show "▲ $*" $RED 1>&2
}

# Print warning message
#
# 1: Message (String)
#
# Code: No
# Echo: No
warn() {
  show "▲ $*" $YELLOW 1>&2
}

# Show message about unknown option
#
# 1: Option name (String)
#
# Code: No
# Echo: No
showOptWarn() {
  error "Error! Unknown option $1"
  exit 1
}

# Show usage info
#
# Code: No
# Echo: No
usage() {
  show ""
  show "${CL_BOLD}Usage:${CL_NORM} rbbuild ${CL_GREEN}{options}${CL_NORM} def-file ${CL_DARK}target-dir${CL_NORM}"
  show ""
  show "${CL_BOLD}Options${CL_NORM}"
  show ""
  showo "--threads, -t"           "Number of threads for build process"                                       "num"
  showo "--no-patch, -np"         "Skip patch directives in definition file"
  showo "--cc-comp, -cc"          "Path to C compiler"                                                        "path/name"
  showo "--cxx-comp, -cxx"        "Path to C++ compiler" "path"                                               "path/name"
  showo "--ignore-checksums, -ic" "Skip checksum check"
  showo "--ignore-loadavg, -il"   "Ignore check for high LA"
  showo "--mirror, -m"            "Mirror name for downloading source archives from it"                       "name"
  showo "--mirror-list, -L"       "Show list of all available mirrors"
  showo "--dl-cache, -dc"         "Path to download cache"                                                    "path"
  showo "--rbenv, -r"             "Automatically install to RBEnv"
  showo "--name, -rn"             "Define name of ruby in RBEnv ${CL_DARK}(--rbenv is required)${CL_NORM}"    "name"
  showo "--proxy, -P"             "Use HTTP proxy on given host and port"                                     "url"
  showo "--debug, -D"             "Don't remove build directory and other build data after installation"
  showo "--output, -O"            "Output path ${CL_DARK}(default /dev/stdout)${CL_NORM}"                     "path"
  showo "--quiet, -q"             "Quiet mode"
  showo "--verbose, -V"           "Verbose mode"
  showo "--tmp, -T"               "Path to temporary directory ${CL_DARK}(used for unpacking files and build process)${CL_NORM}"  "path"
  showo "--yes, -y"               "Answer \"yes\" to all questions"
  showo "--continue, -C"          "Don't clean prefix directory before build"
  showo "--no-color, -nc"         "Don't use colors in output"
  showo "--no-spinner, -ns"       "Don't show spinner"
  showo "--help, -h"              "Show this help message"
  showo "--version, -v"           "Show information about version"
  show ""
  show "${CL_BOLD}Examples${CL_NORM}"
  show ""
  show "  rbbuild 2.7.5 /home/user/ruby-2.7.5 -t 4 -m essentialkaos"
  show "  ${CL_IT_DARK}Build 2.7.5 with sources from EK mirror using 4 threads${CL_NORM}"
  show ""
  show "  rbbuild 3.0.5 /home/user/ruby-3.0.5"
  show "  ${CL_IT_DARK}Build 3.0.5 and install it to given directory${CL_NORM}"
  show ""
  show "  rbbuild 3.1.1 -r"
  show "  ${CL_IT_DARK}Build 3.1.1 and install it to RBEnv${CL_NORM}"
  show ""
  show "  rbbuild 3.1.1 | more"
  show "  ${CL_IT_DARK}Show def file for 3.1.1${CL_NORM}"
  show ""
}

# Show version and license info
#
# Code: No
# Echo: No
about() {
  show ""
  show "${CL_BL_CYAN}${APP}${CL_NORM} ${CL_CYAN}${VER}${CL_NORM} - Utility for compiling and installing different Ruby versions"
  show ""
  show "Copyright (C) 2009-$(date +%Y) ESSENTIAL KAOS" $DARK
  show "Apache License, Version 2.0 <https://www.apache.org/licenses/LICENSE-2.0>" $DARK
  show ""
}

## OPTIONS PARSING 5 ###########################################################

if [[ $# -eq 0 ]] ; then
  main
fi

unset opt optn optm optv optt optk

optv="$*" ; optt=""

while [[ -n "$1" ]] ; do
  if [[ "$1" =~ \  && -n "$optn" ]] ; then
    declare "$optn=$1"

    unset optn && shift && continue
  elif [[ $1 =~ ^-{1}[a-zA-Z0-9]{1,2}+.*$ ]] ; then
    optm=${1:1}

    if [[ \ $SHORT_OPTS\  =~ \ $optm:!?([a-zA-Z0-9_]*) ]] ; then
      opt="${BASH_REMATCH[1]}"
    else
      declare -F showOptWarn &>/dev/null && showOptWarn "-$optm"
      shift && continue
    fi

    if [[ -z "$optn" ]] ; then
      optn=$opt
    else
      # shellcheck disable=SC2015
      [[ -z "$optk" ]] && ( declare -F showOptValWarn &>/dev/null && showOptValWarn "--$optn" ) || declare "$optn=true"
      optn=$opt
    fi

    if [[ ! $SUPPORTED_OPTS\  =~ !?$optn\  ]] ; then
      declare -F showOptWarn &>/dev/null && showOptWarn "-$optm"
      shift && continue
    fi

    if [[ ${BASH_REMATCH[0]:0:1} == "!" ]] ; then
      declare "$optn=true" ; unset optn ; optk=true
    else
      unset optk
    fi

    shift && continue
  elif [[ "$1" =~ ^-{2}[a-zA-Z]{1}[a-zA-Z0-9_-]+.*$ ]] ; then
    opt=${1:2}

    if [[ $opt == *=* ]] ; then
      IFS="=" read -ra opt <<< "$opt"

      optm="${opt[0]}" ; optm=${optm//-/_}

      if [[ ! $SUPPORTED_OPTS\  =~ $optm\  ]] ; then
        declare -F showOptWarn &>/dev/null && showOptWarn "--${opt[0]//_/-}"
        shift && continue
      fi

      # shellcheck disable=SC2015
      [[ -n "${!optm}" && $MERGEABLE_OPTS\  =~ $optm\  ]] && declare "$optm=${!optm} ${opt[*]:1:99}" || declare "$optm=${opt[*]:1:99}"

      unset optm && shift && continue
    else
      # shellcheck disable=SC2178
      opt=${opt//-/_}

      if [[ -z "$optn" ]] ; then
        # shellcheck disable=SC2128
        optn=$opt
      else
        # shellcheck disable=SC2015
        [[ -z "$optk" ]] && ( declare -F showOptValWarn &>/dev/null && showOptValWarn "--$optn" ) || declare "$optn=true"
        # shellcheck disable=SC2128
        optn=$opt
      fi

      if [[ ! $SUPPORTED_OPTS\  =~ !?$optn\  ]] ; then
        declare -F showOptWarn &>/dev/null && showOptWarn "--${optn//_/-}"
        shift && continue
      fi

      if [[ ${BASH_REMATCH[0]:0:1} == "!" ]] ; then
        declare "$optn=true" ; unset optn ; optk=true
      else
        unset optk
      fi

      shift && continue
    fi
  else
    if [[ -n "$optn" ]] ; then
      # shellcheck disable=SC2015
      [[ -n "${!optn}" && $MERGEABLE_OPTS\  =~ $optn\  ]] && declare "$optn=${!optn} $1" || declare "$optn=$1"

      unset optn && shift && continue
    fi
  fi

  optt="$optt $1" ; shift
done

[[ -n "$optn" ]] && declare "$optn=true"

unset opt optn optm optk

# shellcheck disable=SC2015,SC2086
[[ -n "$KEEP_OPTS" ]] && main $optv || main ${optt:1}

################################################################################
