#!/usr/bin/env bash
# shellcheck disable=SC2034

################################################################################

if [[ -n "${SCRIPT_DEBUG}" ]] ; then
  set -x
fi

################################################################################

# App name (String)
APP="RBBuild Def Utils"

# App version (String)
VER="2.1.2"

################################################################################

NORM=0
BOLD=1
ITLC=3
UNLN=4
RED=31
GREEN=32
YELLOW=33
BLUE=34
MAG=35
CYAN=36
GREY=37
DARK=90

CL_NORM="\e[${NORM}m"
CL_BOLD="\e[${BOLD}m"
CL_ITLC="\e[${ITLC}m"
CL_UNLN="\e[${UNLN}m"
CL_RED="\e[${RED}m"
CL_GREEN="\e[${GREEN}m"
CL_YELLOW="\e[${YELLOW}m"
CL_BLUE="\e[${BLUE}m"
CL_MAG="\e[${MAG}m"
CL_CYAN="\e[${CYAN}m"
CL_GREY="\e[${GREY}m"
CL_DARK="\e[${DARK}m"
CL_BL_RED="\e[${BOLD};${RED}m"
CL_BL_GREEN="\e[${BOLD};${GREEN}m"
CL_BL_YELLOW="\e[${BOLD};${YELLOW}m"
CL_BL_BLUE="\e[${BOLD};${BLUE}m"
CL_BL_MAG="\e[${BOLD};${MAG}m"
CL_BL_CYAN="\e[${BOLD};${CYAN}m"
CL_BL_GREY="\e[${BOLD};${GREY}m"
CL_IT_DARK="\e[${ITLC};${DARK}m"
CL_BG_RED="\e[7m${CL_RED}"
CL_BG_GREEN="\e[7m${CL_GREEN}"
CL_BG_YELLOW="\e[7m${CL_YELLOW}"
CL_BG_BLUE="\e[7m${CL_BLUE}"
CL_BG_MAG="\e[7m${CL_MAG}"
CL_BG_CYAN="\e[7m${CL_CYAN}"
CL_BG_GREY="\e[7m${CL_GREY}"

################################################################################

# List of supported options (String)
SUPPORTED_OPTS="!help !version !remove !force author !no_color"

# List of supported short options (String)
SHORT_OPTS="h:!help v:!version r:!remove f:!force a:author nc:!no_color"

# Path to configuration file (String)
PREFS_FILE="$HOME/.config/rbbuild/rbdef.conf"

# Current working dir (String)
CWD=$(pwd)

################################################################################

ARCH_TYPES=(".tar.gz" ".tgz" ".tar.bz2" ".tbz2" ".tb2" ".tbz" "tar.xz" ".txz" ".zip" ".7z")
PATCH_TYPES=(".patch" ".diff")

################################################################################

author=""

################################################################################

# Main function
#
# *: All arguments except parsedrbinstall
#
# Code: No
# Echo: No
main() {
  if [[ -n "$no_color" || -n "$NO_COLOR" ]] || [[ ! -c /dev/stdout && -z $FAKETTY ]] ; then
    unset NORM BOLD CL_ITLC UNLN RED GREEN YELLOW BLUE MAG CYAN GREY DARK
    unset CL_NORM CL_BOLD CL_UNLN CL_RED CL_GREEN CL_YELLOW CL_BLUE CL_MAG CL_CYAN CL_GREY CL_DARK
    unset CL_BL_RED CL_BL_GREEN CL_BL_YELLOW CL_BL_BLUE CL_BL_MAG CL_BL_CYAN CL_BL_GREY CL_IT_DARK
    unset CL_BG_RED CL_BG_GREEN CL_BG_YELLOW CL_BG_BLUE CL_BG_MAG CL_BG_CYAN CL_BG_GREY
    no_color=true
  fi

  if [[ -n "$version" ]] ; then
    about 
    doExit
  fi

  if [[ $# -eq 0 || -n "$help" ]] ; then 
    usage
    doExit
  fi

  prepare

  local cmd="$1"

  shift

  case $cmd in
    "repack")  repack "$@" ;;
    "replace") replace "$@" ;;
    "crc")     crc "$@" ;;
    "rec")     getRecord "$@" ;;
    "proc")    proc "$@" ;;
    *)         error "Unknown command $cmd" ;;
  esac

  doExit $?
}

# Check system before executing script
#
# Code: No
# Echo: No
prepare() {
  if ! isAppInstalled "curl" ; then
    error "This utility require curl. Install it first."
    doExit 1
  fi

  if ! isAppInstalled "bc" ; then
    error "This utility require bc. Install it first."
    doExit 1
  fi

  if ! isAppInstalled "7za" ; then
    error "This utility require p7zip. Install it first."
    doExit 1
  fi

  if ! isAppInstalled "zstd" ; then
    error "This utility require zstd. Install it first."
    doExit 1
  fi
}

# Repack data to tar.zst
#
# *: Files
#
# Code: No
# Echo: No
repack() {
  local file url file_name arch_dir
  local prev_size new_size size_diff

  for file in "$@" ; do
    if [[ $file =~ http:|https:|ftp: ]] ; then
      url=$(parseArgsInString "$file")
      file_name=$(basename "$url")

      show "Downloading ${CL_BOLD}$file_name${CL_NORM}… "

      if ! download "$url" "$file_name" ; then
        error "Can't download file"
        return 1
      fi
    elif checkPerms "FR" "$file" ; then
      file_name="$file"
    else
      error "Can't find file for repack"
      return 1
    fi

    if ! checkArch "$file_name" ; then
      rm -f "$file_name"
      return 1
    fi

    showm "Unpacking file ${CL_BOLD}$file_name${CL_NORM}… "

    arch_dir=$(unpack "$file_name")

    if [[ -z "$arch_dir" ]] ; then
      show "FAIL" $RED
      error "Can't unpack file $file_name. Exiting…"
      return 1
    fi

    show "DONE" $GREEN
    showm "Packing to ${CL_BOLD}$arch_dir.tzst${CL_NORM}… "

    rm -rf "$arch_dir.tzst" &> /dev/null

    # Max compression using all cores
    ZSTD_CLEVEL=19 ZSTD_NBTHREADS=$(getconf _NPROCESSORS_ONLN) tar -I 'zstd' -cf "$arch_dir.tzst" "$arch_dir"

    prev_size=$(getHumanFileSize "$file_name")
    new_size=$(getHumanFileSize "$arch_dir.tzst")
    size_diff=$(getSizeDiff "$file_name" "$arch_dir.tzst")

    show "${CL_GREEN}DONE${CL_NORM} ${CL_DARK}(${prev_size} → ${new_size} / ${size_diff}%)${CL_NORM}"

    [[ -n "$remove" ]] && rm -rf "$file_name" &> /dev/null

    rm -rf "$arch_dir" &> /dev/null

    crc "$arch_dir.tzst"
  done

  return 0
}

# Create record line for given url
#
# 1: URL (String)
#
# Code: No
# Echo: rbdef data record (String)
getRecord() {
  local url file_name file_type checksum

  url=$(parseArgsInString "$1")
  file_name=$(basename "$url")
  file_type=$(getFileType "$file_name")

  if [[ "$file_name" != "git" && "$file_name" != "hg" && "$file_name" != "svn" ]] ; then
    show "Downloading ${CL_BOLD}$file_name${CL_NORM}… "

    if ! download "$url" "$file_name" ; then
      error "Can't download file"
      doExit
    fi

    checksum=$(makeCRC "$file_name")

    show "Record:" $BOLD

    if [[ "$file_name" == "package" ]] ; then
      clean_name=$(cleanName "$file_name" "${ARCH_TYPES[@]}")
      show "  $file_type: \"$clean_name\" \"$url\" \"$checksum\""
    else
      show "  $file_type: \"$url\" \"$checksum\""
    fi

    rm -rf "$file_name" &> /dev/null
  else
    error "Can't generate record for repository"
    doExit 1
  fi
}

# Replace record in def file by pattern
#
# *: List of def files
#
# Code: No
# Echo: No
replace() {
  local line_num tmp_file orig_file target_name

  show "Enter search pattern:" $CYAN
  read -r -e -p "> " pattern_answer
  show ""

  show "Enter replace string:" $CYAN
  read -r -e -p "> " replace_answer
  show ""

  for file in "$@" ; do
    target_name=$(basename "$file")

    showm "Processing file ${CL_BOLD}$target_name${CL_NORM}… "

    if ! checkPerms "FRW" "$file" ; then
      show "FAIL" $RED
      error "You don't have enough permissions for modify file $file"
      continue
    fi

    tmp_file=$(mktemp)
    orig_file=$(mktemp)

    grep -v "#" "$file" >> "$orig_file"
    grep -v "#" "$file" >> "$tmp_file"

    if grep -q "$pattern_answer" "$orig_file" ; then
      line_num=$(grep -n "$pattern_answer" "$orig_file" | head -1 | cut -f1 -d":")

      for line in $line_num ; do
        replaceLine "$line_num" "$replace_answer" "$tmp_file"
      done

      echo -n > "$file"
      addHeader "$file"

      cat "$tmp_file" >> "$file"
      rm -f "$tmp_file" "$orig_file" &> /dev/null

      show "DONE" $GREEN
    else
      show "NOT FOUND" $YELLOW
      rm -f "$tmp_file" "$orig_file" &> /dev/null
    fi
  done
}

# Generate checksums def records
#
# *: List of def files
#
# Code: No
# Echo: No
proc() {
  local line tmp_file target_name

  for file in "$@" ; do
    target_name=$(basename "$file")

    showm "Processing file ${CL_BOLD}${target_name}${CL_NORM}… "

    if ! checkPerms "FRW" "$file" ; then
      show "FAIL" $RED
      if [[ ! -e "$file" ]] ; then
        error "There is no file $file"
      else
        error "You don't have enough permissions for modify file $file"
      fi
      continue
    fi

    tmp_file=$(mktemp)

    addHeader "$tmp_file"

    local rec url crc file_name new_crc

    while read -r line ; do
      if [[ $line =~ patch:|patchset:|package: ]] ; then
        IFS=" " read -r -a rec <<< "${line//\"/}"

        if [[ $line =~ patch:|patchset: ]] ; then
          url="${rec[1]}"
          crc="${rec[2]}"
        else
          url="${rec[2]}"
          crc="${rec[3]}"
        fi

        url=$(parseArgsInString "$url")

        if [[ ${#crc} -eq 40 && -z "$force" ]] ; then
          echo "  $line" >> "$tmp_file" && continue
        fi

        file_name=$(basename "$url")

        if ! checkPerms "FR" "$file_name" || [[ -n "$force" ]] ; then
          if ! download "$url" "$file_name" true ; then
            show "FAIL" $RED
            error "Can't download file $url"
            continue
          else
            showm "↓ " $GREY
          fi
        fi

        new_crc=$(makeCRC "$file_name")

        [[ -n "$remove" ]] && rm -rf "$file_name" &> /dev/null

        if [[ -n "$crc" ]] ; then
          echo "  ${line//\"${crc}\"/\"${new_crc}\"}" >> "$tmp_file"
        else
          echo "  ${line} \"${new_crc}\"" >> "$tmp_file"
        fi
      elif [[ $line =~ git:|svn:|hg: ]] ; then
        echo "  $line" >> "$tmp_file"
      else
        if [[ ${line:0:1} != "#" ]] ; then
          echo "$line" >> "$tmp_file"
        fi
      fi
    done < <(awk 1 "$file")

    cat "$tmp_file" > "$file"

    rm -f "$tmp_file"

    show "DONE" $GREEN
  done
}

# # Generate SHA checksum for given file or url
#
# 1: File or URL (String)
#
# Code: No
# Echo: No
crc() {
  local file crc url file_name

  if checkPerms "FR" "$1" ; then
    file="$1"
    crc=$(makeCRC "$file")
    show "${CL_BOLD}SHA1:${CL_NORM} $crc"
  elif [[ $1 =~ http:|https:|ftp: ]]; then
    url=$(parseArgsInString "$1")
    file_name=$(basename "$url")

    show "Downloading $file_name… "

    if ! download "$url" "$file_name" ; then
      error "Can't download file"
      doExit 1
    fi

    crc=$(makeCRC "$file_name")

    show "${CL_BOLD}SHA1:${CL_NORM} $crc"

    [[ -n "$remove" ]] && rm -rf "$file_name" &> /dev/null
  else
    error "Can't make CRC checksum for file $1. File is not exist or not readable."
    doExit 1
  fi
}

# Check archive
#
# 1: Archive file (String)
#
# Code: Yes
# Echo: No
checkArch() {
  local file_size
  local arch="$1"

  file_size=$(stat -c '%s' "$arch")

  if [[ $file_size -lt 1024 ]] ; then
    error "Looks like file $arch is not an archive file"
    return 1
  fi

  return 0
}

# Unpack archive
#
# 1: Archive file (String)
#
# Code: No
# Echo: Name of directory in archive (String)
unpack() {
  local name arch

  arch="$1"

  rm -rf .tmp &> /dev/null
  mkdir .tmp &> /dev/null

  if [[ $arch =~ .tar.gz$|.tgz$ ]] ; then
    tar xzf "$arch" -C .tmp &> /dev/null
  elif [[ $arch =~ .tar.bz2$|.tbz2$ ]] ; then
    tar xjf "$arch" -C .tmp &> /dev/null
  elif [[ $arch =~ .tar.xz$|.txz$ ]] ; then
    tar xJf "$arch" -C .tmp &> /dev/null
  elif [[ $arch =~ .7z$ ]] ; then
    7za x "$arch" -o.tmp &> /dev/null
  elif [[ $arch =~ .zip$ ]] ; then
    unzip "$arch" -d .tmp &> /dev/null
  else
    echo "" && return 1
  fi

  # shellcheck disable=SC2181
  if [[ $? -ne 0 ]] ; then
    rm -rf .tmp &> /dev/null
    echo "" && return 1
  fi

  name=$(ls .tmp)

  if [[ $name =~ truffleruby ]] ; then
    mv ".tmp/$name" ."/${name//-linux-amd64/}"
    name=${name//-linux-amd64/}
  else
    mv ".tmp/$name" .
  fi

  rm -rf .tmp &> /dev/null

  echo "$name" && return 0
}

# Generate SHA-1 checksum
#
# 1: File (String)
#
# Code: No
# Echo: SHA checksum (String)
makeCRC() {
  sha1sum "$1" | cut -f1 -d" "
}

# Get file type
#
# 1: File name or URL (String)
#
# Code: No
# Echo: Type (package|git|patch) (String)
getFileType() {
  local file_name="$1"

  if [[ $file_name =~ .tar.gz$|.tgz$|.tar.bz2$|.tbz2$|.tar.xz$|.txz$|.tar.zst$|.tzst$|.zip$|.7z$ ]] ; then
    echo "package" && return 0
  elif [[ $file_name =~ .git ]]; then
    echo "git" && return 0
  elif [[ $file_name =~ .hg ]]; then
    echo "hg" && return 0
  elif [[ $file_name =~ .svn ]]; then
    echo "svn" && return 0
  elif [[ $file_name =~ .patch$|.diff$ ]]; then
    echo "patch" && return 0
  else
    echo "" && return 1
  fi
}

# Replace parts of name
#
# 1: Name (String)
# *: Replacements
#
# Code: No
# Echo: Result (String)
cleanName() {
  local name rmv

  name="$1"

  shift

  for rmv in "$@" ; do
    name="${name//$rmv/}"
  done

  echo "$name"
}

# Add header comment to def file
#
# 1: Def file (String)
#
# Code: No
# Echo: No
addHeader() {
  local file date

  file="$1"
  date=$(date +"%d/%b/%Y %R:%S")

  echo '# -- [RBdef] --' >> "$file"
  echo "# UPDATED $date by $author" >> "$file"
}

################################################################################

# Download file
#
# 1: File URL (String)
# 2: Output file (String)
# 3: Avoid cache flag (Boolean)
#
# Code: Yes
# Echo: No
download() {
  local path="$1"
  local output="$2"
  local quite="$3"

  local http_code http_code_tmp

  http_code_tmp=$(mktemp)

  if [[ -z "$quite" ]] ; then
    curl -# -L --max-redirs 10 -w "%{http_code}" -o "$output" "$url" 1> "$http_code_tmp"
  else
    curl -s -L --max-redirs 10 -w "%{http_code}" -o "$output" "$url" 1> "$http_code_tmp"
  fi

  http_code=$(cat "$http_code_tmp")

  rm -f "$http_code_tmp" &> /dev/null

  if [[ "$http_code" != "200" ]] ; then
    rm -f "$output" &> /dev/null
    return 1
  fi

  return 0
}

# Check permissions for file or directory
#
# 1: Permissions (String)
# 2: File or directory (String)
#
# Code: No
# Echo: No
checkPerms() {
  local perms path

  perms=$(echo "$1" | tr "[:lower:]" "[:upper:]")
  path="$2"

  for perm in $(echo "$perms" | fold -w1) ; do
    case $perm in
      "R") [[ ! -r "$path" ]] && return 1 ;;
      "W") [[ ! -w "$path" ]] && return 1 ;;
      "E") [[ ! -e "$path" ]] && return 1 ;;
      "D") [[ ! -d "$path" ]] && return 1 ;;
      "F") [[ ! -f "$path" ]] && return 1 ;;
      "S") [[ ! -s "$path" ]] && return 1 ;;
      "H") [[ ! -h "$path" ]] && return 1 ;;
      *) return 1
    esac
  done

  return 0
}

# Replace line in def file
#
# 1: Line number (Number)
# 2: New line (String)
# 3: File (String)
#
# Code: No
# Echo: No
replaceLine() {
  local linenum newline filename curline temp

  linenum="$1"
  newline="$2"
  filename="$3"
  curline=1
  temp=$(mktemp)

  if [[ $newline =~ patch:|patchset:|package: ]] ; then
    newline="  $newline"
  fi

  while IFS='' read -r line ; do
    if [[ $linenum -eq $curline ]] ; then
      echo "$newline" >> "$temp"
    else
      echo "$line" >> "$temp"
    fi

    ((curline++))
  done < "$filename"

  mv "$temp" "$filename"
}

# Parse and evaluate variables in text
#
# 1: Text (String)
#
# Return: none
# Echo: Result (String)
parseArgsInString() {
  local data="$*"

  if [[ ! $data =~ \$ ]] ; then
    echo "$data" && return 0
  else
    local prm_name

    while : ; do
      if [[ "$data" =~ \$\{([A-Za-z0-9_?]{3,})\} ]] ; then
        prm_name="${BASH_REMATCH[1]}"
      else
        break
      fi

      data="${data//$\{$prm_name\}/${!prm_name}}"
    done

    echo "$data" && return 0
  fi
}

# Check required dependencies
#
# *: Required binaries
#
# Code: No
# Echo: No
isAppInstalled() {
  for app in "$@" ; do
    if ! type -P "$app" &> /dev/null ; then
      return 1
    fi
  done

  return 0
}

# Return size diff
#
# 1: File #1 (String)
# 2: file #2 (String)
#
# Code: No
# Echo: Diff (Number)
getSizeDiff() {
  local size1 size2

  size1=$(stat -c '%s' "$1")
  size2=$(stat -c '%s' "$2")

  diff=$(echo "scale=3; 100-((${size2}/${size1})*100)" | bc | sed 's/00$//')

  if [[ ${diff:0:2} == "-." ]] ; then
    diff="-0${diff}"
  elif [[ ${diff:0:1} == "." ]] ; then
    diff="0${diff}"
  fi

  if [[ "${diff:0:1}" == "-" ]] ; then
    echo "+${diff:1:99}"
    return
  fi

  echo "-$diff"
}

# Print human size of file
#
# 1: File (String)
#
# Code: No
# Echo: Size (String)
getHumanFileSize() {
  du -kh "$1" | cut -f1
}

# Exit from utility
#
# 1: Exit code (Number) [Optional]
#
# Code: No
# Echo: No
doExit() {
  exit "${1-0}"
}

################################################################################

# Show message
#
# 1: Message (String)
# 2: Color code (Number) [Optional]
#
# Code: No
# Echo: No
show() {
  if [[ -n "$2" && -z "$no_colors" ]] ; then
    echo -e "\e[${2}m${1}\e[0m"
  else
    echo -e "$*"
  fi
}

# Show message without newline symbol
#
# 1: Message (String)
# 2: Color (Number) [Optional]
#
# Return: none
# Echo: none
showm() {
  if [[ -n "$2" && -z "$no_colors" ]] ; then
    echo -e -n "\e[${2}m${1}\e[0m"
  else
    echo -e -n "$*"
  fi
}

# Show formatted message with option info
#
# 1: Option (String)
# 2: Description (String)
# 3: Arguments (String) [Optional]
#
# Code: No
# Echo: No
showo() {
  local ent_name ent_desc optp optt optf breadcrumbs

  ent_clr="$1"
  ent_name="$2"
  ent_desc="$3"
  ent_args="$4"

  if [[ -n "$DARK" ]] ; then
    breadcrumbs="............................"
  else
    breadcrumbs="                            "
  fi

  if [[ -z "$ent_args" ]] ; then
    optt="$ent_name"
    optf=$(( 28 - ${#optt} ))
    echo -e "  ${ent_clr}${ent_name}${CL_NORM} ${CL_DARK}${breadcrumbs:0:$optf}${CL_NORM} $ent_desc"
  else
    optt="$ent_name $ent_args"
    optf=$(( 28 - ${#optt} ))
    echo -e "  ${ent_clr}${ent_name}${CL_NORM} ${CL_GREY}${optp}${CL_NORM} ${CL_DARK}${breadcrumbs:0:$optf}${CL_NORM} $ent_desc"
  fi
}

# Print error message
#
# 1: Message (String)
#
# Code: No
# Echo: No
error() {
  show "▲ $*" $RED 1>&2
}

# Print warning message
#
# 1: Message (String)
#
# Code: No
# Echo: No
warn() {
  show "▲ $*" $YELLOW 1>&2
}

# Show message about unknown option
#
# 1: Option name (String)
#
# Code: No
# Echo: No
showOptWarn() {
  error "Error! Unknown option $1"
  exit 1
}

# -
#
# Show usage info
#
# Code: No
# Echo: No
usage() {
  show ""
  show "${CL_BOLD}Usage:${CL_NORM} rbdef ${CL_GREEN}{options}${CL_NORM} ${CL_YELLOW}{command}${CL_NORM} arguments…"
  show ""
  show "Commands" $BOLD
  show ""
  showo "$CL_YELLOW" "repack"  "Repack source archive to tar.zst"
  showo "$CL_YELLOW" "replace" "Find and replace records in def files"
  showo "$CL_YELLOW" "proc"    "Add SHA-1 checksum to records in def files"
  showo "$CL_YELLOW" "crc"     "Generate CRC for given file or URL"
  showo "$CL_YELLOW" "rec"     "Create record line from URL"
  show ""
  show "Options" $BOLD
  show ""
  showo "$CL_GREEN" "--remove, -r"    "Remove downloaded sources (use with ${CL_YELLOW}repack${CL_NORM} or ${CL_YELLOW}proc${CL_NORM} command)"
  showo "$CL_GREEN" "--force, -f"     "Always download sources while def processing (use with ${CL_YELLOW}proc${CL_NORM} command)"
  showo "$CL_GREEN" "--author, -a"    "Author of def file (use with ${CL_YELLOW}proc${CL_NORM} command)"
  showo "$CL_GREEN" "--no-color, -nc" "Disable colors in output"
  showo "$CL_GREEN" "--help"          "Show this help message"
  showo "$CL_GREEN" "--version, -v"   "Show information about version"
  show ""
}

# -
#
# Show version and license info
#
# Code: No
# Echo: No
about() {
  show ""
  show "${CL_BL_CYAN}$APP${CL_NORM} ${CL_CYAN}$VER${CL_NORM} — Utility for working with RBBuild def files"
  show ""
  show "Copyright (C) 2009-$(date +%Y) ESSENTIAL KAOS" $DARK
  show "Apache License, Version 2.0 <https://www.apache.org/licenses/LICENSE-2.0>" $DARK
  show ""
}

## PREFS PARSING ###############################################################

unset arg argn argp

PREFS_FILE=${PREFS_FILE//\~/$HOME}

if [[ -n "$PREFS_FILE" && -r "$PREFS_FILE" ]] ; then
  while read -r arg ; do
    [[ -z "$arg" || "$arg" =~ ^\# || "$arg" =~ ^\ +$ ]] && continue
    arg="${arg/: /:}" ; argn="${arg%%:*}" ; argn="${argn//-/_}"
    argp="${arg#*:}" ; argp="${argp/\~/$HOME}"
    [[ "$SUPPORTED_OPTS " =~ $argn\ && -n "$argp" ]] && declare "$argn=$argp"
  done < <(awk 1 "$PREFS_FILE")

  unset arg argn argp
fi

## OPTIONS PARSING 5 ###########################################################

if [[ $# -eq 0 ]] ; then
  main
fi

unset opt optn optm optv optt optk

optv="$*" ; optt=""

while [[ -n "$1" ]] ; do
  if [[ "$1" =~ \  && -n "$optn" ]] ; then
    declare "$optn=$1"

    unset optn && shift && continue
  elif [[ $1 =~ ^-{1}[a-zA-Z0-9]{1,2}+.*$ ]] ; then
    optm=${1:1}

    if [[ \ $SHORT_OPTS\  =~ \ $optm:!?([a-zA-Z0-9_]*) ]] ; then
      opt="${BASH_REMATCH[1]}"
    else
      declare -F showOptWarn &>/dev/null && showOptWarn "-$optm"
      shift && continue
    fi

    if [[ -z "$optn" ]] ; then
      optn=$opt
    else
      # shellcheck disable=SC2015
      [[ -z "$optk" ]] && ( declare -F showOptValWarn &>/dev/null && showOptValWarn "--$optn" ) || declare "$optn=true"
      optn=$opt
    fi

    if [[ ! $SUPPORTED_OPTS\  =~ !?$optn\  ]] ; then
      declare -F showOptWarn &>/dev/null && showOptWarn "-$optm"
      shift && continue
    fi

    if [[ ${BASH_REMATCH[0]:0:1} == "!" ]] ; then
      declare "$optn=true" ; unset optn ; optk=true
    else
      unset optk
    fi

    shift && continue
  elif [[ "$1" =~ ^-{2}[a-zA-Z]{1}[a-zA-Z0-9_-]+.*$ ]] ; then
    opt=${1:2}

    if [[ $opt == *=* ]] ; then
      IFS="=" read -ra opt <<< "$opt"

      optm="${opt[0]}" ; optm=${optm//-/_}

      if [[ ! $SUPPORTED_OPTS\  =~ $optm\  ]] ; then
        declare -F showOptWarn &>/dev/null && showOptWarn "--${opt[0]//_/-}"
        shift && continue
      fi

      # shellcheck disable=SC2015
      [[ -n "${!optm}" && $MERGEABLE_OPTS\  =~ $optm\  ]] && declare "$optm=${!optm} ${opt[*]:1:99}" || declare "$optm=${opt[*]:1:99}"

      unset optm && shift && continue
    else
      # shellcheck disable=SC2178
      opt=${opt//-/_}

      if [[ -z "$optn" ]] ; then
        # shellcheck disable=SC2128
        optn=$opt
      else
        # shellcheck disable=SC2015
        [[ -z "$optk" ]] && ( declare -F showOptValWarn &>/dev/null && showOptValWarn "--$optn" ) || declare "$optn=true"
        # shellcheck disable=SC2128
        optn=$opt
      fi

      if [[ ! $SUPPORTED_OPTS\  =~ !?$optn\  ]] ; then
        declare -F showOptWarn &>/dev/null && showOptWarn "--${optn//_/-}"
        shift && continue
      fi

      if [[ ${BASH_REMATCH[0]:0:1} == "!" ]] ; then
        declare "$optn=true" ; unset optn ; optk=true
      else
        unset optk
      fi

      shift && continue
    fi
  else
    if [[ -n "$optn" ]] ; then
      # shellcheck disable=SC2015
      [[ -n "${!optn}" && $MERGEABLE_OPTS\  =~ $optn\  ]] && declare "$optn=${!optn} $1" || declare "$optn=$1"

      unset optn && shift && continue
    fi
  fi

  optt="$optt $1" ; shift
done

[[ -n "$optn" ]] && declare "$optn=true"

unset opt optn optm optk

# shellcheck disable=SC2015,SC2086
[[ -n "$KEEP_OPTS" ]] && main $optv || main ${optt:1}

################################################################################
