#!/bin/bash
# shellcheck disable=SC1117,SC2034,SC2154

# Start autoconf builder
#
# 1: Package name (String)
# 2: Package build dir (String)
#
# Code: No
# Echo: No
autoconfBuilder() {
  checkVersionCompatibility "1.6.0"

  local pkg pkg_dir fail
  local start_time end_time grc_time

  pkg="$1"
  pkg_dir="$2"

  shift 2

  exportCompilerOpts

  pushd "$pkg_dir" &> /dev/null || printErrorAndExit "Can't set working dir to $pkg_dir"

    showm "Autoconf… "

    [[ -n "$verbose" ]] && show ""

    start_time=$(now)

    exit_protect=true

    spinnerOn

    if [[ -n "$verbose" ]] ; then
      {
        showe "autoconf"
        autoconf || fail=true

      } &>> "$output"
    else
      {

        autoconf || fail=true

      } &>> "$log"
    fi

    spinnerOff

    if [[ -n "$fail" ]] ; then
      unset exit_protect
      buildFailed "$prfx"
      return 1
    fi

    end_time=$(now)
    grc_time=$(getGraceTime "$start_time" "$end_time")

    show "${CL_GREEN}DONE${CL_NORM} ${CL_DARK}($grc_time)${CL_NORM}"

    echo -n > "$log"

    unset exit_protect

  popd &> /dev/null || printErrorAndExit "Can't set working dir"

  buildPackage "$pkg" "$pkg_dir" "default" "$@"
}
