#!/bin/bash

# Start Maglev builder
#
# 1: Package name (String)
# 2: Package build dir (String)
#
# Code: No
# Echo: No
maglevBuilder() {
  checkVersionCompatibility "1.6.0"

  local pkg pkg_dir iopts prfx fail
  local start_time end_time grc_time

  pkg="$1"
  pkg_dir="$2"

  iopts="${INSTOPTS}"
  prfx="${XPREFIX:-${prefix}}"

  exportCompilerOpts

  pushd "$pkg_dir" &> /dev/null

    showm "Building... "

    [[ -n "$verbose" ]] && show ""

    start_time=$(now)

    exit_protect=true

    spinnerOn

    if [[ -n "$verbose" ]] ; then
      { mkdir -p "$prfx"
        [[ $? -ne 0 ]] && fail=true && break
        cp -r . "$prfx"
        [[ $? -ne 0 ]] && fail=true && break

        pushd "$prfx"
          showe "./install.sh $iopts"
          ./install.sh $iopts
          [[ $? -ne 0 ]] && fail=true && break
        popd
      } &>> "$output"
    else
      { mkdir -p "$prfx"
        [[ $? -ne 0 ]] && fail=true && break
        cp -r . "$prfx"
        [[ $? -ne 0 ]] && fail=true && break

        pushd "$prfx"
          ./install.sh $iopts
          [[ $? -ne 0 ]] && fail=true && break
        popd
      } &>> "$log"
    fi

    spinnerOff

    if [[ -n "$fail" ]] ; then
      unset exit_protect
      buildFailed "$prfx"
      return 1
    fi

    pushd "$prfx/bin" &> /dev/null

      ln -fs maglev-ruby ruby
      ln -fs maglev-irb irb

    popd &> /dev/null

    end_time=$(now)
    grc_time=$(getGraceTime "$start_time" "$end_time")

    show "${CL_GREEN}DONE${CL_NORM} ${CL_GREY}($grc_time)${CL_NORM}"

    echo -n > "$log"

    unset exit_protect

  popd &> /dev/null

  show "Run \"maglev start\" to start up the stone before using \"ruby\" or \"irb\"" $BROWN
}
