#!/bin/bash

# Start MRuby builder
#
# 1: Package name (String)
# 2: Package build dir (String)
#
# Code: No
# Echo: No
mrubyBuilder() {
  checkVersionCompatibility "1.6.0"

  local pkg pkg_dir prfx fail
  local start_time end_time grc_time

  pkg="$1"
  pkg_dir="$2"

  prfx="${XPREFIX:-${prefix}}"

  exportCompilerOpts

  pushd "$pkg_dir" &> /dev/null

    showm "Building... "

    [[ -n "$verbose" ]] && show ""

    start_time=$(now)

    exit_protect=true

    spinnerOn

    if [[ -n "$verbose" ]] ; then
      { mkdir -p "$prfx"
        [[ $? -ne 0 ]] && fail=true && break
        showe "ruby ./minirake"
        ruby ./minirake
        [[ $? -ne 0 ]] && fail=true && break
        cp -r build/host/* "$prfx"
        [[ $? -ne 0 ]] && fail=true && break
      } &>> "$output"
    else
      { mkdir -p "$prfx"
        [[ $? -ne 0 ]] && fail=true && break
        ruby ./minirake
        [[ $? -ne 0 ]] && fail=true && break
        cp -r build/host/* "$prfx"
        [[ $? -ne 0 ]] && fail=true && break
      } &>> "$log"
    fi

    spinnerOff

    if [[ -n "$fail" ]] ; then
      unset exit_protect
      buildFailed "$prfx"
      return 1
    fi

    pushd "$prfx/bin" &> /dev/null

      ln -fs mruby ruby
      ln -fs mirb irb

    popd &> /dev/null

    end_time=$(now)
    grc_time=$(getGraceTime "$start_time" "$end_time")

    show "${CL_GREEN}DONE${CL_NORM} ${CL_GREY}($grc_time)${CL_NORM}"

    echo -n > "$log"

    unset exit_protect

  popd &> /dev/null
}