#!/bin/bash
# shellcheck disable=SC1117,SC2034,SC2154

# Start MRuby builder
#
# 1: Package name (String)
# 2: Package build dir (String)
#
# Code: No
# Echo: No
mrubyBuilder() {
  checkVersionCompatibility "1.6.0"

  local pkg pkg_dir prfx fail
  local start_time end_time grc_time

  pkg="$1"
  pkg_dir="$2"

  prfx="${XPREFIX:-${prefix}}"

  exportCompilerOpts

  pushd "$pkg_dir" &> /dev/null || printErrorAndExit "Can't set working dir to $pkg_dir"

    showm "Building… "

    [[ -n "$verbose" ]] && show ""

    start_time=$(now)

    exit_protect=true

    spinnerOn

    if [[ -n "$verbose" ]] ; then
      { 
        
        if [[ -z "$fail" ]] ; then
          mkdir -p "$prfx" || fail=true
        fi
        
        if [[ -z "$fail" ]] ; then
          showe "ruby ./minirake"
          ruby ./minirake || fail=true
        fi
        
        if [[ -z "$fail" ]] ; then
          cp -r build/host/* "$prfx" || fail=true
        fi

      } &>> "$output"
    else
      { 
        
        if [[ -z "$fail" ]] ; then
          mkdir -p "$prfx" || fail=true
        fi
        
        if [[ -z "$fail" ]] ; then
          ruby ./minirake || fail=true
        fi
       
        if [[ -z "$fail" ]] ; then
          cp -r build/host/* "$prfx" || fail=true
        fi

      } &>> "$log"
    fi

    spinnerOff

    if [[ -n "$fail" ]] ; then
      unset exit_protect
      buildFailed "$prfx"
      return 1
    fi

    pushd "$prfx/bin" &> /dev/null || printErrorAndExit "Can't set working dir to $prfx/bin"

      ln -fs mruby ruby
      ln -fs mirb irb

    popd &> /dev/null || printErrorAndExit "Can't set working dir"

    end_time=$(now)
    grc_time=$(getGraceTime "$start_time" "$end_time")

    show "${CL_GREEN}DONE${CL_NORM} ${CL_DARK}($grc_time)${CL_NORM}"

    echo -n > "$log"

    unset exit_protect

  popd &> /dev/null || printErrorAndExit "Can't set working dir"
}