#!/bin/bash

# Start OpenSSL builder
#
# Code: No
# Echo: No
opensslBuilder() {
  checkVersionCompatibility "1.2.0"

  if ! hasBuilder "default" ; then
    show "This build process require default builder."
    doExit 1
  fi

  runBuilder "default" "$@"

  local ssl_dir="$prefix/openssl/ssl"

  [[ ! -f /etc/pki/tls/cert.pem ]] && return 0

  rm -rf "$ssl_dir/certs"

  ln -sf /etc/pki/tls/cert.pem "$ssl_dir/cert.pem" &> /dev/null
  ln -sf /etc/pki/tls/certs "$ssl_dir/certs" &> /dev/null
}