#!/bin/bash
# shellcheck disable=SC1117,SC2034,SC2086,SC2154

# Start rubinius builder
#
# 1: Package name (String)
# 2: Package build dir (String)
#
# Code: No
# Echo: No
rbxBuilder() {
  checkVersionCompatibility "1.6.0"

  requireCompiler

  local pkg pkg_dir copts iopts prfx fail
  local start_time end_time grc_time

  pkg="$1"
  pkg_dir="$2"

  copts="${CONFOPTS}"
  iopts="${INSTOPTS}"
  prfx="${XPREFIX:-${prefix}}"

  exportCompilerOpts

  [[ -z "$gem_prefix" ]] && gem_prefix="$prfx"

  pushd "$pkg_dir" &> /dev/null || printErrorAndExit "Can't set working dir to $pkg_dir"

    showm "Building… "

    [[ -n "$verbose" ]] && show ""

    start_time=$(now)

    exit_protect=true

    spinnerOn

    if [[ $verbose ]] ; then
      {

        if [[ -z "$fail" ]] ; then
          showe "bundle install"
          bundle install || fail=true
        fi

        if [[ -z "$fail" ]] ; then
          showe "./configure --prefix=$prfx $copts"
          ./configure --prefix="$prfx" $copts || fail=true
        fi

        if [[ -z "$fail" ]] ; then
          showe "rake install $iopts --trace"
          rake install $iopts --trace || fail=true
        fi

      } &>> "$output"
    else
      {

        if [[ -z "$fail" ]] ; then
          bundle install || fail=true
        fi

        if [[ -z "$fail" ]] ; then
          ./configure --prefix="$prfx" $copts || fail=true
        fi

        if [[ -z "$fail" ]] ; then
          rake install $iopts || fail=true
        fi

      } &>> "$log"
    fi

    spinnerOff

    if [[ $fail ]] ; then
      unset exit_protect
      buildFailed "$prfx"
      return 1
    fi

    end_time=$(now)
    grc_time=$(getGraceTime "$start_time" "$end_time")

    show "${CL_GREEN}DONE${CL_NORM} ${CL_DARK}($grc_time)${CL_NORM}"

    echo -n > "$log"

    unset exit_protect

  popd &> /dev/null || printErrorAndExit "Can't set working dir"
}
