#!/bin/bash
# shellcheck disable=SC1117,SC2034,SC2154

# Start REE builder
#
# 1: Package name (String)
# 2: Package build dir (String)
#
# Code: No
# Echo: No
reeBuilder() {
  checkVersionCompatibility "1.6.0"

  local pkg pkg_dir copts prfx fail
  local start_time end_time grc_time

  pkg="$1"
  pkg_dir="$2"

  copts="${CONFOPTS}"
  prfx="${XPREFIX:-${prefix}}"

  if isOS "$OS_MACOSX" ; then
    copts="${copts} --no-tcmalloc"
  fi

  pushd "$pkg_dir" &> /dev/null || printErrorAndExit "Can't set working dir to $pkg_dir"

    showm "Building... "

    [[ -n "$verbose" ]] && show ""

    start_time=$(now)

    exit_protect=true

    spinnerOn

    mkdir -p "$prfx/lib/ruby/gems/1.8/gems"

    if [[ -n "$verbose" ]] ; then
      {

        showe "./installer --auto \"$prfx\" --dont-install-useful-gems \"$copts\""
        ./installer --auto "$prfx" --dont-install-useful-gems "$copts" || fail=true

      } &>> "$output"
    else
      {

        ./installer --auto "$prfx" --dont-install-useful-gems "$copts" || fail=true

      } &>> "$log"
    fi

    spinnerOff

    if [[ -n "$fail" ]] ; then
      unset exit_protect
      buildFailed "$prfx"
      return 1
    fi

    end_time=$(now)
    grc_time=$(getGraceTime "$start_time" "$end_time")

    show "${CL_GREEN}DONE${CL_NORM} ${CL_DARK}($grc_time)${CL_NORM}"

    echo -n > "$log"

    unset exit_protect

  popd &> /dev/null || printErrorAndExit "Can't set working dir"
}
