#!/bin/bash
# shellcheck disable=SC1117,SC2034,SC2086,SC2154

# Start ruby builder
#
# 1: Package name (String)
# 2: Package build dir (String)
#
# Code: No
# Echo: No
rubyBuilder() {
  checkVersionCompatibility "1.6.0"

  local pkg pkg_dir prfx ruby_bin fail installer
  local start_time end_time grc_time

  pkg="$1"
  pkg_dir="$2"

  prfx="${XPREFIX:-${prefix}}"
  ruby_bin="$prfx/bin/ruby"

  pushd "$pkg_dir" &> /dev/null || printErrorAndExit "Can't set working dir to $pkg_dir"

    showm "Building… "

    [[ -n "$verbose" ]] && show ""

    start_time=$(now)

    if checkPerms "FR" "setup.rb" ; then
      installer="setup.rb"
    elif checkPerms "FR" "installer.rb" ; then
      installer="installer.rb"
    else
      show "FAIL" $RED
      show ""
      show "Can't find installer file."
      doExit 1
    fi

    exit_protect=true

    spinnerOn

    if [[ -n "$verbose" ]] ; then
      {

        showe "$ruby_bin $installer"
        $ruby_bin "$installer" || fail=true

      } &>> "$output"
    else
      {

        $ruby_bin "$installer" || fail=true

      } &>> "$log"
    fi

    spinnerOff

    if [[ -n "$fail" ]] ; then
      unset exit_protect
      buildFailed "$prfx"
      return 1
    fi

    fixDLDFlags "$prfx"

    end_time=$(now)
    grc_time=$(getGraceTime "$start_time" "$end_time")

    show "${CL_GREEN}DONE${CL_NORM} ${CL_DARK}($grc_time)${CL_NORM}"

    echo -n > "$log"

    unset exit_protect

  popd &> /dev/null || printErrorAndExit "Can't set working dir"
}

# Fix DLDFLAGS for Ruby 2.4+
#
# 1: Prefix dir (String)
#
# Code: No
# Echo: No
fixDLDFlags() {
	local prfx="$1"
	local config

	config=$(find "$prfx" -name "rbconfig.rb")

	if [[ -z "$config" ]] ; then
		return
	fi

	sed -i '/CONFIG\["DLDFLAGS"\]/c \ \ CONFIG["DLDFLAGS"]=""' "$config" &> /dev/null
}
