#!/bin/bash

# Start ruby builder
#
# 1: Package name (String)
# 2: Package build dir (String)
#
# Code: No
# Echo: No
rubyBuilder() {
  checkVersionCompatibility "1.6.0"

  local pkg pkg_dir prfx ruby_bin fail installer
  local start_time end_time grc_time

  pkg="$1"
  pkg_dir="$2"

  prfx="${XPREFIX:-${prefix}}"
  ruby_bin="$prfx/bin/ruby"

  pushd "$pkg_dir" &> /dev/null

    showm "Building... "

    [[ -n "$verbose" ]] && show ""

    start_time=$(now)

    if checkPerms "FR" "setup.rb" ; then
      installer="setup.rb"
    elif checkPerms "FR" "installer.rb" ; then
      installer="installer.rb"
    else
      show "FAIL" $RED
      show ""
      show "Can't find installer file."
      doExit "$ERROR_UNKNOWN"
    fi

    exit_protect=true

    spinnerOn

    if [[ -n "$verbose" ]] ; then
      { showe "$ruby_bin $installer"
        $ruby_bin "$installer"
        [[ $? -ne 0 ]] && fail=true && break
      } &>> "$output"
    else
      { $ruby_bin "$installer"
        [[ $? -ne 0 ]] && fail=true && break
      } &>> "$log"
    fi

    spinnerOff

    if [[ -n "$fail" ]] ; then
      unset exit_protect
      buildFailed "$prfx"
      return 1
    fi

    end_time=$(now)
    grc_time=$(getGraceTime "$start_time" "$end_time")

    show "${CL_GREEN}DONE${CL_NORM} ${CL_GREY}($grc_time)${CL_NORM}"

    echo -n > "$log"

    unset exit_protect

  popd &> /dev/null
}
