#!/bin/bash

# Start topaz builder
#
# 1: Package name (String)
# 2: Package build dir (String)
#
# Code: No
# Echo: No
topazBuilder() {
  checkVersionCompatibility "1.2.0"

  local pkg pkg_dir prfx fail
  local start_time end_time grc_time

  pkg="$1"
  pkg_dir="$2"

  prfx="${XPREFIX:-${prefix}}"

  pushd "$pkg_dir" &> /dev/null

    showm "Building... "

    start_time=$(now)

    exit_protect=true

    spinnerOn

    if [[ -n "$verbose" ]] ; then
      { mkdir -p "$prfx"
        [[ $? -ne 0 ]] && fail=true
        cp -r . "$prfx"
        [[ $? -ne 0 ]] && fail=true

        pushd "$prfx/bin"
          ln -fs topaz ruby
          [[ $? -ne 0 ]] && fail=true
        popd
      } &>> "$output"
    else
      { mkdir -p "$prfx"
        [[ $? -ne 0 ]] && fail=true
        cp -r . "$prfx"
        [[ $? -ne 0 ]] && fail=true

        pushd "$prfx/bin"
          ln -fs topaz ruby
          [[ $? -ne 0 ]] && fail=true
        popd
      } &>> "$log"
    fi

    spinnerOff

    if [[ -n "$fail" ]] ; then
      unset exit_protect
      buildFailed "$prfx"
      return 1
    fi

    end_time=$(now)
    grc_time=$(getGraceTime "$start_time" "$end_time")

    show "${CL_GREEN}DONE${CL_NORM} ${CL_GREY}($grc_time)${CL_NORM}"

    echo -n > "$log"

    unset exit_protect

  popd &> /dev/null
}