#!/bin/bash

# Start topaz builder
#
# 1: Package name (String)
# 2: Package build dir (String)
#
# Code: No
# Echo: No
topazBuilder() {
  checkVersionCompatibility "1.2.0"

  local pkg pkg_dir prfx fail
  local start_time end_time grc_time

  pkg="$1"
  pkg_dir="$2"

  prfx="${XPREFIX:-${prefix}}"

  pushd "$pkg_dir" &> /dev/null

    showm "Building... "

    [[ -n "$verbose" ]] && show ""

    start_time=$(now)

    exit_protect=true

    spinnerOn

    if [[ -n "$verbose" ]] ; then
      {

        if [[ -z "$fail" ]] ; then
          mkdir -p "$prfx" || fail=true
        fi

        if [[ -z "$fail" ]] ; then
          cp -r . "$prfx" || fail=true
        fi

        pushd "$prfx/bin"

          if [[ -z "$fail" ]] ; then
            ln -fs topaz ruby || fail=true
          fi

        popd
      } &>> "$output"
    else
      {

        if [[ -z "$fail" ]] ; then
          mkdir -p "$prfx" || fail=true
        fi

        if [[ -z "$fail" ]] ; then
          cp -r . "$prfx" || fail=true
        fi

        pushd "$prfx/bin"

          if [[ -z "$fail" ]] ; then
            ln -fs topaz ruby || fail=true
          fi

        popd
      } &>> "$log"
    fi

    spinnerOff

    if [[ -n "$fail" ]] ; then
      unset exit_protect
      buildFailed "$prfx"
      return 1
    fi

    end_time=$(now)
    grc_time=$(getGraceTime "$start_time" "$end_time")

    show "${CL_GREEN}DONE${CL_NORM} ${CL_DARK}($grc_time)${CL_NORM}"

    echo -n > "$log"

    unset exit_protect

  popd &> /dev/null
}