name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  Defs:
    name: Defs Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run defs tests
        run: .github/scripts/def_check.sh SOURCES/defs

  Shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    needs: Defs

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check scripts with Shellcheck
        uses: essentialkaos/shellcheck-action@v1
        with:
          files: install.sh SOURCES/mass-builder SOURCES/rbdef SOURCES/rbbuild SOURCES/libexec/*.shx SOURCES/libexec/builders/*.shx

  Perfecto:
    name: Perfecto
    runs-on: ubuntu-latest

    needs: Defs

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check specs with Perfecto
        uses: essentialkaos/perfecto-action@v2
        with:
          files: rbbuild.spec rbbuild-defs.spec
