name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  Defs:
    name: Defs Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run defs tests
        run: .scripts/script.sh SOURCES/defs

  Shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest

    needs: Defs

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check scripts with Shellcheck
        uses: essentialkaos/shellcheck-action@v1
        with:
          files: install.sh SOURCES/rbdef SOURCES/rbbuild SOURCES/blds/*

  Perfecto:
    name: Perfecto
    runs-on: ubuntu-latest

    needs: Defs

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check spec with Perfecto
        uses: essentialkaos/perfecto-action@v2
        with:
          files: rbbuild.spec rbbuild-defs.spec
